server:
    port: 9003

spring:
    application:
        name: eureka-consumer

    # 允许重复名称的bean定义
    main:
        allow-bean-definition-overriding: true

eureka:
    instance:
        # 使用IP注册
        prefer-ip-address: ${use-ip-address}
    # 注册地址
    client:
        service-url:
            defaultZone: ${register.url}
