server:
    port: 8082
    tomcat:
        max-threads: 1000
        min-spare-threads: 10

spring:
    application:
        name: lemon-apply

    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB

    # 允许重复名称的bean定义
    main:
        allow-bean-definition-overriding: true

    # 引入其他yml配置
    profiles:
        include:

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lemon?characterEncoding=utf8&useSSL=false
        username: root
        password: 1234

    jpa:
        generateDdl: false
        properties:
            hibernate:
                show_sql: false
                format_sql: false
    #                database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

eureka:
    instance:
        # 使用IP注册
        prefer-ip-address: true
    #注册地址
    client:
        service-url:
            defaultZone: http://eureka.lemon.com/eureka/

logging:
    #日志
    config: classpath:logback-prod.xml

# redission配置文件
redission_config: redisson-config-prod.yml
# 搜索索引位置
video_index_path:
# 视频上传路径
video_source_path:
# 图片上传路径
image_source_path: