# 支付宝配置
com:
    lemon:
        pay:
            returnUrl: http://www.lemon.com/p/pay/toSuccess
            notifyUrl: http://www.lemon.com/p/pay/callback
            url: https://openapi.alipaydev.com/gateway.do
            charset: GBK
            format: json
            signType: RSA2
            appId:
            appPrivateKey:
            aliPayPublicKey:


