server:
    port: 8083
    tomcat:
        max-threads: 1000
        min-spare-threads: 10

spring:
    application:
        name: lemon-pay

    # 允许上传文件和请求大小
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB

    # 允许重复名称的bean定义
    main:
        allow-bean-definition-overriding: true

    profiles:
        include:

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://106.15.200.151:3306/lemon?characterEncoding=utf8&useSSL=false
        username: lemon
        password: 1234

    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: false
                # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

logging:
    # 日志
    config: classpath:logback-dev.xml

# redission配置文件
redission_config: redisson-config-prod.yml
# 支付宝配置
com:
    lemon:
        pay:
            returnUrl: http://www.lemon.com/p/pay/toSuccess
            notifyUrl: http://www.lemon.com/p/pay/callback
            url: https://openapi.alipaydev.com/gateway.do
            charset: GBK
            format: json
            signType: RSA2
            appId:
            appPrivateKey:
            aliPayPublicKey:


