server:
    port: 8083
    tomcat:
        max-threads: 1000
        min-spare-threads: 10

logging:
    #日志
    config: classpath:logback-prod.xml

spring:
    application:
        name: lemon-apply

    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB

    # 允许重复名称的bean定义
    main:
        allow-bean-definition-overriding: true

    profiles:
        include: lemon-prod

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.221.130:3306/lemon?characterEncoding=utf8&useSSL=false
        username: root
        password: 1234

    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: false

    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
