server:
    port: 8081
    tomcat:
        max-threads: 1000
        min-spare-threads: 10

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lemon?useUnicode=true&useSSL=false
        username: lemon
        password: lemon@SJP123

    jpa:
        generateDdl: true
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

    redis:
        host: 127.0.0.1
        port: 6379
        password:
        jedis:
            pool:
                max-active: 100
                max-idle: 100
                min-idle: 10
                max-wait: 6000
