server:
    port: 8081
    tomcat:
        max-threads: 1000
        min-spare-threads: 10

spring:
    profiles:
        include: logback

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lemon?useUnicode=true&useSSL=false
        username: root
        password: 1234

    jpa:
        generateDdl: false
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

