server:
    port: ${server.port}
    tomcat:
        max-threads: ${tomcat-max-threads}
        min-spare-threads: ${tomcat-min-spare-threads}

spring:
    # 允许重复名称的bean定义，为了解决Fegin重复命名无法启动的问题
    main:
        allow-bean-definition-overriding: true

    datasource:
        type: ${jdbc.type}
        driver-class-name: ${jdbc.driver-class-name}
        url: ${jdbc.url}
        username: ${jdbc.username}
        password: ${jdbc.password}

    jpa:
        generateDdl: ${hibernate.generateDdl}
        properties:
            hibernate:
                show_sql: ${hibernate.show_sql}
                format_sql: ${hibernate.format_sql}
                database-platform: ${hibernate.database-platform}

    jackson:
        time-zone: ${jackson.time-zone}
        date-format: ${jackson.date-format}

eureka:
    instance:
        # 使用IP注册
        prefer-ip-address: ${use-ip-address}
    # 注册地址
    client:
        service-url:
            defaultZone: ${register.url}

# actuator 监控
management:
    endpoints:
        web:
            basePath: ${actuator.web.url}
            # 监控请求
            exposure:
                include: ${actuator.web.exposure.include}
    server:
        port: ${actuator.server.port}
    endpoint:
        health:
            show-details: ${actuator.health.show-details}
    # micrometer监控
    metrics:
        tags:
            application: ${spring.application.name}

logging:
    #日志
    config: classpath:logback-${spring.cloud.config.profile}.xml

# redission配置
redission:
    config: ${redission.single.config}

