server:
    port: 9001

eureka:
    instance:
        hostname: eureka-service
    server:
        # 清理无效节点时间间隔，默认60000ms=60s
        eviction-interval-timer-in-ms: 60000
    client:
        # 不注册自己
        register-with-eureka: false
        # 获取服务
        fetch-registry: false
        # 注册中心地址
        service-url:
            defaultZone: http://localhost:${server.port}/eureka/
