server:
    port: 8001

spring:
    application:
        name: eureka-server

eureka:
    environment: ${spring.cloud.config.profile}
    instance:
        hostname: ${spring.application.name}
    server:
        # 清理无效节点时间间隔，默认60000ms=60s
        eviction-interval-timer-in-ms: 30000
        # 是否开启自我保护
        enable-self-preservation: true
    client:
        # 此实例是否从注册中心获取注册信息
        fetch-registry: false
        # 是否将此实例注册到注册中心
        register-with-eureka: false
        # 注册中心地址
        service-url:
            defaultZone: http://eureka.shijianpeng.top/eureka/

# 日志
logging:
    config: classpath:logback-${spring.cloud.config.profile}.xml

# actuator 监控
management:
    endpoints:
        web:
            basePath: /appInfo
            exposure:
                # 开启全部监控请求
                include: "*"
    server:
        # 监控端口
        port: 7001
    endpoint:
        health:
            # heath展示全部信息 其他配置 when_authorized、never，
            show-details: always
    # micrometer监控
    metrics:
        tags:
            application: ${spring.application.name}

info:
    app.name: eureka-provider
    company.name: lemon.shijianpeng.top
    build.artifactId: eureka-server
    build.version: 0.0.1