server:
    port: 9001

spring:
    application:
        name: eureka-server

eureka:
    instance:
        hostname: eureka-server
    server:
        # 清理无效节点时间间隔，默认60000ms=60s
        eviction-interval-timer-in-ms: 60000
    client:
        # 不注册自己
        register-with-eureka: false
        # 获取服务
        fetch-registry: false
        # 注册中心地址
        service-url:
            defaultZone: http://eureka.shijianpeng.top/eureka/

# actuator 监控
management:
    endpoints:
        web:
            basePath: /appInfo
            exposure:
                # 开启全部监控请求
                include: "*"
    server:
        # 监控端口
        port: 10001
    endpoint:
        health:
            # heath展示全部信息 其他配置 when_authorized、never，
            show-details: always

info:
    app.name: eureka-provider
    company.name: lemon.shijianpeng.top
    build.artifactId: eureka-server
    build.version: 0.0.1