server:
    port: 9002
    tomcat:
        max-threads: ${tomcat-max-threads}
        min-spare-threads: ${tomcat-min-spare-threads}

spring:
    datasource:
        type: ${jdbc.type}
        driver-class-name: ${jdbc.driver-class-name}
        url: ${jdbc.url}
        username: ${jdbc.username}
        password: ${jdbc.password}

    jpa:
        generateDdl: ${hibernate.generateDdl}
        properties:
            hibernate:
                show_sql: ${hibernate.show_sql}
                format_sql: ${hibernate.format_sql}
                database-platform: ${hibernate.database-platform}

eureka:
    instance:
        # 使用ip进行注册
        prefer-ip-address: ${use-ip-address}
    client:
        serviceUrl:
            defaultZone: ${register.url}

# actuator 监控
management:
    endpoints:
        web:
            basePath: ${actuator.web.url}
            # 监控请求
            exposure:
                include: ${actuator.web.exposure.include}
    server:
        port: ${actuator.server.port}
    endpoint:
        health:
            show-details: ${actuator.health.show-details}

info:
    app.name: eureka-provider
    company.name: lemon.shijianpeng.top
    build.artifactId: eureka-provider
    build.version: 0.0.1

logging:
    #日志
    config: classpath:logback-${spring.cloud.config.profile}.xml

# redission配置文件
redission:
    config: ${redission.single.config}