server:
    port: 8090
    tomcat:
        max-threads: 1000
        min-spare-threads: 10

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${jdbc.url}
        username: ${jdbc.username}
        password: ${jdbc.password}

    jpa:
        generateDdl: ${hibernate.generateDdl}
        properties:
            hibernate:
                show_sql: ${hibernate.show_sql}
                format_sql: ${hibernate.format_sql}
                database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

logging:
    #日志
    config: classpath:logback-${spring.cloud.config.profile}.xml

# redission配置文件
redission_config: redisson-config-${spring.cloud.config.profile}.yml

