server:
  port: 8090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.221.130:3306/lemon?characterEncoding=utf8&useSSL=false
    username: lemon
    password: 1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false

version-config: ${version}